---
- name: Set-up Ingress Controller
  command: "{{ item }}"
  loop:
    - kubectl apply -f {{ role_path }}/files/ingress_files/common/ns-and-sa.yaml
    - kubectl apply -f {{ role_path }}/files/ingress_files/rbac
    - kubectl apply -f {{ role_path }}/files/ingress_files/default-server-secret.yaml
    - kubectl apply -f {{ role_path }}/files/ingress_files/common/nginx-config.yaml
    - kubectl apply -f {{ role_path }}/files/ingress_files/common/ingress-class.yaml
    - kubectl apply -f {{ role_path }}/files/ingress_files/common/crds
    - kubectl apply -f {{ role_path }}/files/ingress_files/deployment/appprotect-dos-arb.yaml
    - kubectl apply -f {{ role_path }}/files/ingress_files/appprotect-dos-arb-svc.yaml
    - kubectl apply -f {{ role_path }}/files/ingress_files/deployment/nginx-ingress.yaml
    - kubectl apply -f {{ role_path }}/files/ingress_files/nginx-ingress.yaml
    # - kubectl create -f {{ role_path }}/files/ingress_files/nodeport.yaml
    - kubectl apply -f {{ role_path }}/files/ingress_files/loadbalancer.yaml
    - kubectl patch svc nginx-ingress -n nginx-ingress -p '{"spec":{"externalIPs":["20.203.206.162"]}}'
