---
- name: Initialize Kubernetes Cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf
  become: yes
  register: kubeadm_init_output

- name: Configure kubectl for the current user
  command: "{{ item }}"
  become: yes
  loop:
    - mkdir -p $HOME/.kube
    - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - mkdir -p /home/azureuser/.kube
    - cp -i /etc/kubernetes/admin.conf /home/azureuser/.kube/config
    # - chown $(id -u):$(id -g) $HOME/.kube/config
  when: kubeadm_init_output.rc == 0

- name: Change ownership of Kubernetes config file
  file:
    path: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  become: yes
  when: kubeadm_init_output.rc == 0

- name: add label to node for public ip and untaint master node
  command: "{{ item }}"
  loop:
  - kubectl taint nodes --all node-role.kubernetes.io/control-plane-
  - kubectl label nodes "{{ node_name }}" haspublicip=true --overwrite
  become: yes

- command: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
  become: yes

- name: install ingress-nginx controller with helm
  command: "{{ item }}"
  loop:
  - helm repo add nginx-stable https://helm.nginx.com/stable
  - helm repo update
  - helm upgrade --install nginx-ingress nginx-stable/nginx-ingress --set rbac.create=true
  become: yes
