---
- name: Initialize Kubernetes Cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf
  become: yes
  register: kubeadm_init_output

- name: Configure kubectl for the current user
  command: "{{ item }}"
  become: yes
  loop:
    - mkdir -p $HOME/.kube
    - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - mkdir -p /home/azureuser/.kube
    - cp -i /etc/kubernetes/admin.conf /home/azureuser/.kube/config
    # - chown $(id -u):$(id -g) $HOME/.kube/config
  when: kubeadm_init_output.rc == 0

- debug:
    msg: "{{ ansible_env.HOME }}"
- debug:
    msg: "{{ ansible_env.USER }}"

- name: Change ownership of Kubernetes config file
  file:
    path: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  become: yes
  when: kubeadm_init_output.rc == 0
