---
- name: Install Kubernetes and Docker
  include_tasks: install_kubernetes.yml

- name: Initialize Kubernetes Cluster
  include_tasks: initialize_kubernetes.yml

- name: Set-up Ingress Controller
  include_tasks: ingress_set_up.yml
