---
app_namespace: "todo-app"

app_name: "todo-app"
app_service_name: "todo-app"

sql_name: "mysql"
sql_service_name: "mysql"

persistent_volume_name: "mysql-pv"
persistent_volume_claim_name: "mysql-pv-claim"

ingress_name: "ingress"


app_labels:
  key: "app"
  value: "todo-app"

sql_labels:
  key: "app"
  value: "mysql"

pv_labels:
  key: "type"
  value: "local"

app_replica_count: 1
mysql_replica_count: 1

# to never be hardcoded like this
mysql_root_password: "Password!123"
mysql_database: "todo"

sql_secret_name: "mysql-secret"

ingress_host: "172.17.0.1:80"

ip_of_VM: "20.203.138.129"
