---
- name: Build Docker Image for My Application
  docker_image:
    name: "{{ docker_image_name }}:{{ docker_image_tag }}"
    path: "{{ docker_build_context }}"
    dockerfile: "{{ dockerfile_path }}"
  become: yes

- name: output docker images
  command: docker images
  debug:
    var: command_output.stdout_lines
