---
- name: Build Docker Image for My Application
  community.docker.docker_image:
    name: "{{ docker_image_name }}"
    build: "{{ docker_build_context }}"
    dockerfile: "{{ dockerfile_path }}"
  become: yes


- name: Print Docker Image Build Output
  debug:
    var: command_output.stdout_lines

# - name: output docker images
#   command: docker images
#   debug:
#     var: command_output.stdout_lines
