---
- name: Build Docker Image for My Application
  community.docker.docker_image:
    name: "{{ docker_image_name }}"
    tag: "{{ docker_image_tag }}"
    build:
      path: "{{ docker_build_context }}"
    source: build
  become: yes

- name: Tag and push to docker hub
  community.docker.docker_image:
    name: "{{ docker_image_name }}:{{ docker_image_tag }}"
    repository: "{{ docker_image_name }}:{{ docker_image_tag }}"
    push: true
    source: local
