---
- name: Create a Kubernetes Namespace for the Application
  k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy Application Deployment
  k8s:
    name: app-deployment
    namespace: "{{ namespace }}"
    definition: "{{ role_path }}/templates/app-deployment.yaml.j2"
    state: present

- name: Deploy MySQL Deployment
  k8s:
    name: mysql-deployment
    namespace: "{{ namespace }}"
    definition: "{{ role_path }}/templates/mysql-deployment.yaml.j2"
    state: present
