---
- name: Create a Kubernetes Namespace for the Application
  k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- command: mkdir -p "{{ role_path }}/files"
  become: yes

- name: jinja2
  template:
    src: "{{ role_path }}/templates/app-deployment.yaml.j2"
    dest: "{{ role_path }}/files/app-deployment.yaml"

# - name: Deploy Application Deployment
#   k8s:
#     name: app-deployment
#     namespace: "{{ namespace }}"
#     definition: "{{ role_path }}/files/app-deployment.yaml"
#     state: present

# debug message
- debug:
    msg: "Deploying application deployment"

- command: kubectl apply -f "{{ role_path }}/files/app-deployment.yaml"
  become: yes

- name: Deploy MySQL Deployment
  k8s:
    name: mysql-deployment
    namespace: "{{ namespace }}"
    definition: "{{ role_path }}/templates/mysql-deployment.yaml.j2"
    state: present
